authentication/urls.py
from django.urls import path
from . import views
app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('choose_profile', views.choose_profile, name='choose_profile'),
    path('logout', views.logout_view, name='logout_view'),
    path('sign_up', views.sign_up, name='sign_up'),
]

author/urls.py
from django.urls import path
from django.conf.urls import include, url  
from . import views
from .views import index

app_name = 'author'

urlpatterns=[
     url('index', views.index,name="index"),
     path('<int:track_id>/edit',views.edit,name="edit"),
]

conference_manager/urls.py
from django.urls import path
from . import views

app_name = 'conference_manager'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_track', views.create_track, name='create_track'),
    path('view_tracks', views.view_tracks, name='view_tracks'),
    path('add_user', views.add_user, name='add_user'),
    path('view_users', views.view_users, name='view_users'),
    path('view_user/<slug:username>', views.view_user, name='view_user'),
    path('view_track/<int:pk>', views.view_track, name='view_track'),
    path('delete_track/<int:pk>', views.delete_track, name='delete_track'),
    path('delete_user/<int:pk>', views.delete_user, name='delete_user'),
]

conference_system/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace="authentication")),
    path('author/', include('author.urls', namespace="author")),
    path('reviewer/', include('reviewer.urls', namespace="reviewer")),
    path('track_chair/', include('track_chair.urls', namespace="track_chair")),
    path('conference_chair/', include('conference_chair.urls', namespace="conference_chair")),
    path('registration_manager/', include('registration_manager.urls', namespace="registration_manager")),
    path('conference_manager/', include('conference_manager.urls', namespace="conference_manager")),
    path('payment_app/', include('payment_app.urls', namespace="payment_app")),
    path('email_system/',include('email_system.urls',namespace="email_system")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

email_system/urls.py
# sendemail/urls.py
from django.contrib import admin
from django.urls import path
from . import views
#app_name='sendemail'
app_name = 'email_system'
urlpatterns = [
    path('drafts/',views.display_draft,name='display'),
    path('customise/<int:pk>/',views.edit_draft,name='edit_draft'),
    
]

conference_manager/models.py
from django.db import models
from authentication.models import CustomUser

from author.models import ResearchPaper
from reviewer.models import ReviewReport
# Create your models here.
class Track(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='author')
    reviewer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='reviewer')
    track_chair = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='track_chair')
    description = models.TextField(blank = True, null = True)
    paper = models.ForeignKey(ResearchPaper,on_delete=models.CASCADE,related_name='respaper',null=True)
    report = models.ForeignKey(ReviewReport,on_delete=models.CASCADE,related_name='respaper',null=True)
    paper_submitted = models.BooleanField(default = False)
    report_submitted = models.BooleanField(default = False)
    report_approved = models.BooleanField(default = False)

conference_manager/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import get_object_or_404, render, redirect
from authentication.models import *
from django.http import HttpResponse
from .models import *
from email_system import urls
# Create your views here.

def index(request):
    return render(request, 'conference_manager/index.html', {})

def create_track(request):
    if request.method == "GET":
        authors = CustomUser.objects.filter(roles__id = 1)
        reviewers = CustomUser.objects.filter(roles__id = 2)
        track_chairs = CustomUser.objects.filter(roles__id = 3)
        print(authors, reviewers, track_chairs)
        response = {}
        response['authors'] = authors
        response['reviewers'] = reviewers
        response['track_chairs'] = track_chairs

        return render(request, 'conference_manager/create_track.html', response)
    elif request.method == "POST":
        author = CustomUser.objects.get(username = request.POST['author'])
        reviewer = CustomUser.objects.get(username = request.POST['reviewer'])
        track_chair = CustomUser.objects.get(username = request.POST['track_chair'])
        track = Track.objects.create(author = author, reviewer = reviewer, track_chair = track_chair, description = request.POST['description'])
        authors = CustomUser.objects.filter(roles__id = 1)
        reviewers = CustomUser.objects.filter(roles__id = 2)
        track_chairs = CustomUser.objects.filter(roles__id = 3)
        print(track)
        response = {
            'success': True,
            'authors': authors,
            'reviewers': reviewers,
            'track_chairs': track_chairs,
        }
        return render(request, 'conference_manager/create_track.html', response)

def view_tracks(request):
    tracks = Track.objects.all()
    response = {}
    response['tracks'] = tracks
    return render(request, 'conference_manager/view_tracks.html', response)

def add_user(request):
    if request.method == "GET":
        roles = Role.objects.all()
        response = {}
        response['roles'] = roles
        return render(request, 'conference_manager/add_user.html', response)
    elif request.method == "POST":
        print(request.POST)
        u = CustomUser.objects.create(username=request.POST['username'], first_name = request.POST['first_name'], last_name = request.POST['last_name'], email=request.POST['email'])
        u.set_password(request.POST['password'])
        u.save()
        u.roles.add(Role.objects.get(id = request.POST['role']))
        roles = Role.objects.all()
        response = {
            'success': True,
            'roles': roles
        }
        return render(request, 'conference_manager/add_user.html', response)

def view_users(request):
    users = CustomUser.objects.all()
    for user in users:
        user.r = user.roles.all()
        print(user.r)
    response = {}
    response['users'] = users
    print(users)
    return render(request, 'conference_manager/view_users.html', response)

def view_user(request, username):
    if request.method == "GET":
        try:
            user = CustomUser.objects.get(username=username)
            user.r = user.roles.all()
            all_roles = Role.objects.all()
            not_assigned_roles = []
            for role in all_roles:
                if role not in user.r:
                    not_assigned_roles.append(role)
            print(not_assigned_roles)
            response = {}
            response['user'] = user
            response['not_assigned_roles'] = not_assigned_roles
            return render(request, 'conference_manager/view_user.html', response)
        except:
            return view_users(request)

    elif request.method == "POST":
        try:
            print(request.POST)
            user = CustomUser.objects.get(username=username)
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.email = request.POST['email']
            user.username = request.POST['username']
            user.roles.clear()
            try:
                value = request.POST['Author']
                user.roles.add(Role.objects.get(id=1))
            except:
                pass
            try:
                value = request.POST['Reviewer']
                user.roles.add(Role.objects.get(id=2))
            except:
                pass
            try:
                value = request.POST['Track Chair']
                user.roles.add(Role.objects.get(id=3))
            except:
                pass
            try:
                value = request.POST['Conference Chair']
                user.roles.add(Role.objects.get(id=4))
            except:
                pass
            try:
                value = request.POST['Registration Manager']
                user.roles.add(Role.objects.get(id=5))
            except:
                pass
            try:
                value = request.POST['Conference Manager']
                user.roles.add(Role.objects.get(id=6))
            except:
                pass
            user.save()
            user.r = user.roles.all()
            all_roles = Role.objects.all()
            not_assigned_roles = []
            for role in all_roles:
                if role not in user.r:
                    not_assigned_roles.append(role)
            response = {}
            response['user'] = user
            response['not_assigned_roles'] = not_assigned_roles
            response['success'] = True
            return render(request, 'conference_manager/view_user.html', response)
        except:
            return view_users(request)

def view_track(request, pk):
    if request.method == "GET":
        track = Track.objects.get(pk = pk)
        authors = CustomUser.objects.filter(roles__id = 1)
        reviewers = CustomUser.objects.filter(roles__id = 2)
        track_chairs = CustomUser.objects.filter(roles__id = 3)
        response = {
            'track': track,
            'authors': authors,
            'reviewers': reviewers,
            'track_chairs': track_chairs
        }
        return render(request, 'conference_manager/view_track.html', response)
    elif request.method == "POST":
        print(request.POST)
        track = Track.objects.get(pk = pk)
        track.author = CustomUser.objects.get(username=request.POST['author'])
        track.reviewer = CustomUser.objects.get(username=request.POST['reviewer'])
        track.track_chair = CustomUser.objects.get(username=request.POST['track_chair'])
        track.description = request.POST['description']
        track.save()
        authors = CustomUser.objects.filter(roles__id = 1)
        reviewers = CustomUser.objects.filter(roles__id = 2)
        track_chairs = CustomUser.objects.filter(roles__id = 3)
        response = {
            'track': track,
            'authors': authors,
            'reviewers': reviewers,
            'track_chairs': track_chairs,
            'success': True
        }
        return render(request, 'conference_manager/view_track.html', response)

def delete_track(request, pk):
    try:
        Track.objects.get(pk=pk).delete()
        return view_tracks(request)
    except:
        return view_tracks(request)

def delete_user(request, pk):
    try:
        CustomUser.objects.get(pk=pk).delete()
        return view_users(request)
    except:
        return view_users(request)

templates/conference_manager/create_track.html
{% extends 'conference_manager/template.html' %}

{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col-8">
            <div class="container-fluid" style="margin-top:10%;">
                    <form action="{% url 'conference_manager:create_track' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="author" class="col-sm-2 col-form-label">Author</label>
                                <div class="col-sm-10">
                                        <select class="form-control" name="author" required>
                                            {% for author in authors %}
                                                <option value={{author.username}}>{{ author.first_name}} {{ author.last_name }}</option>
                                            {% endfor %}
                                        </select>
                                </div>
                                    
                            </div>
                            <br>
                            <div class="form-group row">
                                    <label for="author" class="col-sm-2 col-form-label">Reviewer</label>
                                    <div class="col-sm-10">
                                            <select class="form-control" name="reviewer" required>
                                                {% for reviewer in reviewers %}
                                                    <option value={{reviewer.username}}>{{ reviewer.first_name}} {{ reviewer.last_name }}</option>
                                                {% endfor %}
                                            </select>
                                    </div>
                                        
                                </div>
                                <br>
                                <div class="form-group row">
                                        <label for="author" class="col-sm-2 col-form-label">Track Chair</label>
                                        <div class="col-sm-10">
                                                <select class="form-control" name="track_chair" required>
                                                    {% for track_chair in track_chairs %}
                                                        <option value={{track_chair.username}}>{{ track_chair.first_name}} {{ track_chair.last_name }}</option>
                                                    {% endfor %}
                                                </select>
                                        </div>
                                            
                                    </div>
                                    <div class="text-center"> 
                                    <button type="submit" class="btn btn-secondary">Create Track</button>
                                    </div>
                    </form>
            </div>
        </div>
        <div class="col">
        
        </div>
    </div>
</div>
{% endblock %}

templates/conference_manager/index_old.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="{% static 'reviewer/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Home</title>
  </head>
  <style>
  body {
    height: 100%;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    background: #70bg32;
    background-repeat:no-repeat;
    background: -webkit-linear-gradient(rgb(197, 199, 204), rgb(135, 137, 142), rgb(197, 199, 204));
    background: -moz-linear-gradient(rgb(197, 199, 204), rgb(135, 137, 142), rgb(197, 199, 204));
    background: -ms-linear-gradient(rgb(197, 199, 204), rgb(135, 137, 142), rgb(197, 199, 204));
    background: -o-linear-gradient(rgb(197, 199, 204), rgb(135, 137, 142), rgb(197, 199, 204));
    background: linear-gradient(rgb(197, 199, 204), rgb(135, 137, 142), rgb(197, 199, 204));
    height: 100%;
    margin: 0;
    background-repeat: no-repeat;
    background-attachment: fixed;
}
  </style>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id="mainNav">
          <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="{% url 'authentication:index' %}">Conference Manager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="{% url 'payment_app:index' %}">Pay Fee</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="{% url 'authentication:logout_view' %}">Logout</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      <!-- <div style="
        display: flex;
        align-items: center;
        justify-content: center;
      ";> -->
      <div class="mx-auto"> 
          <br><br><br>
        <a href="{% url 'conference_manager:create_conference' %}" class="btn btn-secondary" role="button" style="margin:7%;">Create Conference</a>
        <a href="{% url 'conference_manager:view_conferences' %}" class="btn btn-secondary" role="button" style="margin:7%;">View Conferences</a>
        <a href="{% url 'conference_manager:view_tracks' %}" class="btn btn-secondary" role="button" style="margin:9%;" >View Tracks</a>
        <a href="{% url 'conference_manager:create_track' %}" class="btn btn-secondary" role="button" style="margin:7%;">Create Track</a>
        <a href="{% url 'conference_manager:add_user' %}" class="btn btn-secondary" role="button" style="margin:7%;">Add User</a>
        <a href="{% url 'conference_manager:view_users' %}" class="btn btn-secondary" role="button" style="margin:7%;">View Users</a>
      </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/conference_manager/template.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="{% static 'reviewer/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <title>Home</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id="mainNav">
                <div class="container">
                  <a class="navbar-brand js-scroll-trigger" href="{% url 'authentication:index' %}">Conference Manager</a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'conference_manager:view_conferences' %}">View Conferences</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'conference_manager:create_conference' %}">Create Conference</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'conference_manager:view_tracks' %}">View Tracks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'conference_manager:create_track' %}">Create Track</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'conference_manager:add_user' %}">Add User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'conference_manager:view_users' %}">View Users</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'authentication:logout_view' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'email_system:display' %}">Customize Templates</a>
                        </li>
                    </ul>
                  </div>
                </div>
        </nav>
<br>
<br>        

    <main role="main" class="container">
        {% block content %}
        {% endblock %}

    </main><!-- /.container -->
    <script src="{% static 'js/a.js' %}"></script>
    <script src="{% static 'js/b.js' %}"></script>
    <script src="{% static 'author/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/conference_manager/view_track.html
{% extends 'conference_manager/template.html' %}

{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col-8">
            <div class="container-fluid" style="margin-top:10%;">
                    <form action="{% url 'conference_manager:view_track' pk=track.pk %}" method="POST">
                            {% csrf_token %}
                            {% if success %}
                                <div class="alert alert-success">
                                        <strong>Success!</strong> The details were updated.
                                      </div>
                                {% endif %}
                            <div class="form-group row">
                                <label for="author" class="col-sm-2 col-form-label">Author</label>
                                <div class="col-sm-10">
                                        <select class="form-control" name="author" required>
                                            {% for author in authors %}
                                                {% if author == track.author %}
                                                <option value={{author.username}} selected>{{ author.first_name}} {{ author.last_name }}</option>
                                                {% else %}
                                                <option value={{author.username}}>{{ author.first_name}} {{ author.last_name }}</option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                </div>
                                    
                            </div>
                            <br>
                            <div class="form-group row">
                                    <label for="author" class="col-sm-2 col-form-label">Reviewer</label>
                                    <div class="col-sm-10">
                                            <select class="form-control" name="reviewer" required>
                                                {% for reviewer in reviewers %}
                                                    {% if reviewer == track.reviewer %}
                                                    <option value={{reviewer.username}} selected>{{ reviewer.first_name}} {{ reviewer.last_name }}</option>
                                                    {% else %}
                                                    <option value={{reviewer.username}}>{{ reviewer.first_name}} {{ reviewer.last_name }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                    </div>
                                        
                                </div>
                                <br>
                                <div class="form-group row">
                                        <label for="author" class="col-sm-2 col-form-label">Track Chair</label>
                                        <div class="col-sm-10">
                                                <select class="form-control" name="track_chair" required>
                                                    {% for track_chair in track_chairs %}
                                                        {% if reviewer == track.reviewer %}
                                                        <option value={{track_chair.username}} selected>{{ track_chair.first_name}} {{ track_chair.last_name }}</option>
                                                        {% else %}
                                                        <option value={{track_chair.username}}>{{ track_chair.first_name}} {{ track_chair.last_name }}</option>
                                                        {% endif %}
                                                    {% endfor %}
                                                </select>
                                        </div>
                                            
                                    </div>
                                    <br>
                                    <div class="form-group row">
                                            <label for="author" class="col-sm-2 col-form-label">Description</label>
                                            <div class="col-sm-10">
                                                    <input type="text" class="form-control" rows="5" name="description" value="{{ track.description }}"></textarea>
                                            </div>
                                                
                                        </div>
                                    <br>
                                    <div class="text-center"> 
                                        <button type="submit" style="display:inline-block"class="btn btn-secondary text-center">Update Track</button>
                                        <a href="{% url 'conference_manager:delete_track' pk=track.pk %}" class="btn btn-danger text-center" role="button">Delete Track</a>
                                    </div>
                                    

                    </form>
            </div>
        </div>
        <div class="col">
        
        </div>
    </div>
</div>
{% endblock %}

templates/conference_manager/view_user.html
{% extends 'conference_manager/template.html' %}

{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col-8">
                <div class="container-fluid" style="margin-top:10%;">
                        <form action="{% url 'conference_manager:view_user' username=user.username %}" method="POST">
                                {% csrf_token %}
                                {% if success %}
                                <div class="alert alert-success">
                                        <strong>Success!</strong> The details were saved.
                                      </div>
                                {% endif %}
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">First Name</label>
                                    <div class="col-sm-10">
                                            <input type="text" class="form-control" value="{{ user.first_name }}" name="first_name">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Last Name</label>
                                        <div class="col-sm-10">
                                                <input type="text" class="form-control" value="{{ user.last_name }}" name="last_name">
                                        </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Username</label>
                                        <div class="col-sm-10">
                                                <input type="text" class="form-control" value="{{ user.username }}" name="username">
                                        </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Email ID</label>
                                        <div class="col-sm-10">
                                                <input type="text" class="form-control" value="{{ user.email }}" name="email">
                                        </div>
                                </div>
                                <div class="form-group row">
                                    <h2 class="col-sm-10 col-form-label">Roles</h2>
                                </div>
                                {% for role in user.r %}
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="{{ role }}" checked=true>
                                        <label class="form-check-label" >
                                            {{ role }}
                                        </label>
                                    </div>
                                    <br>
                                {% endfor %}
                                {% for role in not_assigned_roles %}
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="{{ role }}">
                                        <label class="form-check-label" >
                                            {{ role }}
                                        </label>
                                    </div>
                                    <br>
                                {% endfor %}
                            
                                <div class="text-center"> 
                                    <button type="submit" style="display:inline-block" class="btn btn-secondary">Save</button>
                                    <a href="{% url 'conference_manager:delete_user' pk=user.pk %}" class="btn btn-danger text-center" role="button">Delete User</a>
                                </div>
                        </form>
                </div>
        </div>
        <div class="col">
        
        </div>
    </div>
</div>
{% endblock %}