author/urls.py
from django.urls import path
from django.conf.urls import include, url  
from . import views
from .views import index

app_name = 'author'

urlpatterns=[
     url('index', views.index,name="index"),
     path('<int:track_id>/edit',views.edit,name="edit"),
]

conference_system/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace="authentication")),
    path('author/', include('author.urls', namespace="author")),
    path('reviewer/', include('reviewer.urls', namespace="reviewer")),
    path('track_chair/', include('track_chair.urls', namespace="track_chair")),
    path('conference_chair/', include('conference_chair.urls', namespace="conference_chair")),
    path('registration_manager/', include('registration_manager.urls', namespace="registration_manager")),
    path('conference_manager/', include('conference_manager.urls', namespace="conference_manager")),
    path('payment_app/', include('payment_app.urls', namespace="payment_app")),
    path('email_system/',include('email_system.urls',namespace="email_system")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

email_system/urls.py
# sendemail/urls.py
from django.contrib import admin
from django.urls import path
from . import views
#app_name='sendemail'
app_name = 'email_system'
urlpatterns = [
    path('drafts/',views.display_draft,name='display'),
    path('customise/<int:pk>/',views.edit_draft,name='edit_draft'),
    
]

payment_app/urls.py
from django.urls import path
from . import views

app_name = 'payment_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact',views.contact_form,name='contact'),
    path('<int:payment_id>/status', views.status, name='status'),
    path('<int:payment_id>/wait', views.wait, name='wait'),
    path('<int:payment_id>/complete', views.complete, name='complete'),
    path('thankyou', views.thankyou, name='thankyou'),
]

payment_app/models.py
from django.db import models

# Create your models here.

from authentication.models import CustomUser
# Create your models here.
import datetime 
class Payment(models.Model):
    credit_card_no = models.CharField(max_length=20)
    cvv = models.IntegerField(default = 0)
    expiry_date = models.DateField('expiration date', default = datetime.datetime.today())
    amount = models.IntegerField(default = 200)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null = True)
    payment_date = models.DateTimeField('Date paid')
    started = models.BooleanField(default = False)
    ongoing = models.BooleanField(default = False)
    approved = models.BooleanField(default = False)
    completed = models.BooleanField(default = False)

    def __str__(self):
     return self.user.username

payment_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

class collectPaymentForm(forms.Form):
    credit_card_no = forms.CharField(help_text = "Enter your credit card no.",max_length=20)
    amount = forms.IntegerField()
    cvv = forms.IntegerField()
    expiry_date = forms.DateField()

    def clean_expiry_date(self):
        data = self.cleaned_data['expiry_date']

        if data < timezone.now().date():
            raise ValidationError(_('Card expired!'))

        return data

class ContactForm(forms.Form):
    email_id = forms.CharField(help_text = "abc@xyz.com",required=True)
    #contact_number = forms.IntegerField()
    subject = forms.CharField(max_length=20)
    message = forms.CharField(widget=forms.Textarea, required=True)

payment_app/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import get_object_or_404, render, redirect
from authentication.models import CustomUser
from django.http import HttpResponse,BadHeaderError
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.template.loader import get_template
from django.template import Context
import sys
import datetime

from payment_app.forms import collectPaymentForm, ContactForm

from payment_app.models import Payment
from email_system.models import draft

def index(request):
    try:
        payment = Payment.objects.get(user = request.user)
        return render(request, 'payment_app/status.html', {'payment':payment})
    except:
        payment = Payment()
        
        if request.method == 'POST':
            credit_card_form = collectPaymentForm(request.POST)

            if credit_card_form.is_valid():
                payment.credit_card_no = credit_card_form.cleaned_data['credit_card_no']
                payment.amount = credit_card_form.cleaned_data['amount']
                payment.cvv = credit_card_form.cleaned_data['cvv']
                payment.expiry_date = credit_card_form.cleaned_data['expiry_date']
                payment.user = request.user
                payment.payment_date = datetime.datetime.now()
                payment.started = True
                payment.save()
                
                subject="Thanks!"
                o=draft.objects.get(title="Payment")
                message=o.text
                to_email=request.user.email
                username=payment.user
                to_email="myusernameanusha@gmail.com"
                ctx={
                'username': username,
                'message_body': message
                }
                try:
                    send_mail(subject, get_template('templates_path/pay_email.html').render(ctx), 'anush.meh@gmail.com', [to_email])
                except:
                    print("Send mail failed")
                    return render(request,'payment_app/error.html')
                return render(request, 'payment_app/status.html', {'payment':payment})
    return render(request, 'payment_app/index.html')
    

def wait(request, payment_id):
    payment = get_object_or_404(Payment, pk = payment_id)
    payment.ongoing = True
    payment.started = False
    payment.save()
    return render(request, 'payment_app/status.html', {'payment':payment})

def complete(request, payment_id):
    payment = get_object_or_404(Payment, pk = payment_id)
    payment.approved = True
    payment.completed = True
    payment.save()
    return render(request, 'payment_app/status.html', {'payment':payment})

def status(request, payment_id):
    payment = get_object_or_404(Payment, pk = payment_id)

    return render(request, 'payment_app/status.html', {'payment':payment})

def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            to_email = form.cleaned_data['email_id']
            message = form.cleaned_data['message']
            print(to_email)
            print(subject)
            print(message)
            try:
                send_mail(subject, message, 'anush.meh@gmail.com', [to_email])
            except:
                print("Error:",sys.exc_info()[0])
                return render(request,'payment_app/error.html')
            return redirect('http://127.0.0.1:8000/payment_app/thankyou')
    if request.method=='GET':
        form=ContactForm()
    return render(request, "payment_app/contact.html",{'form':form})
def thankyou(request):
    return render(request,"payment_app/thankyou.html")

templates/payment_app/contact.html
{% load static %}
 <!DOCTYPE html>
<html lang="en">
   <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
     <title>Contact Us</title>
     <!-- Bootstrap core CSS -->
    <link href="{% static 'reviewer/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'reviewer/tabs.css' %}" rel="stylesheet">
    <link href="{% static 'reviewer/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  </head>
   <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <h2 style="color:aliceblue;">Contact Us</h2>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'track_chair:index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'authentication:index' %}">Back</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
     <section id="tabs">
        <div class="container">
          <div class="row">
              <div class="col">
               </div>
              <div class="col-8">
                  <div class="container-fluid" style="margin-top:10%;">
                          <form action="" method="POST">
                                  {% csrf_token %}
                                  <div class="form-group row">
                                      <label class="col-sm-2 col-form-label">Email ID</label>
                                      <div class="col-sm-10">
                                              <input type="text" name="email_id" class="form-control" required>
                                      </div>
                                  </div>
                                   <br>
                                   <div class="form-group row">
                                      <label class="col-sm-2 col-form-label">Subject</label>
                                      <div class="col-sm-10">
                                              <input type="text" name="subject" class="form-control" required>
                                      </div>
                                  </div>
                                   <br>
                                   <div class="form-group row">
                                          <label class="col-sm-2 col-form-label">Message</label>
                                          <div class="col-sm-10">
                                                  <input type="textarea" name="message" class="form-control" required>
                                          </div>
                                  </div>
                                   <br>
                                   <div class="text-center">
                                      <button type="submit" class="btn btn-secondary">Send</button>
                                  </div>
                          </form>
                  </div>
              </div>
              <div class="col">
               </div>
          </div>
        </div>
        </section>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'reviewer/bootstrap/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'reviewer/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
   </body>
 </html>

templates/payment_app/error.html
{% load static %}
 <!DOCTYPE html>
<html lang="en">
   <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
     <title>Oops!</title>
     <!-- Bootstrap core CSS -->
    <link href="{% static 'reviewer/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'reviewer/tabs.css' %}" rel="stylesheet">
    <link href="{% static 'reviewer/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  </head>
   <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <h2 style="color:aliceblue;">Contact Us</h2>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'track_chair:index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'authentication:index' %}">Back</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
 <!--{% if error_message %}<p> <strong>{{ error_message }}</strong> </p>{% endif %}-->
     <section id="tabs">
        <div class="container">
          <div class="row">
              <div class="col">
              </div>
              <p>
                <l>
                  <l>
              <h1><center>Looks like there was a problem sending the email. Sorry for the trouble,please try again some time later!</center></h1>
              </p>
              <body style="text-align: center;">
                   <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpSPorOj67jL3VG1EGqxJBPq4yuGFwursJiv4YNwtpACRx8Bd4MA"
                      align="middle"
                      style="
                        display: block;
                        margin-left: auto;
                        margin-right: auto;
                        
                        z-index: 1;"
                      >
               </body>
 </html>

templates/payment_app/index.html
{% extends 'payment_app/template.html' %}

{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col-8">
            <div class="container-fluid" style="margin-top:10%;">
                    <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Credit Card Number</label>
                                <div class="col-sm-10">
                                        <input type="text" name="credit_card_no" class="form-control" required>
                                </div>
                            </div>

                            <br>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Amount</label>
                                <div class="col-sm-10">
                                        <input type="number" name="amount" class="form-control" value= "200" required>
                                </div>
                            </div>

                            <br>



                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Expiry date</label>
                                <div class="col-sm-10">
                                        <input type="date" name="expiry_date" class="form-control" required>
                                </div>
                            </div>

                            <br>

                            <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">CVV</label>
                                    <div class="col-sm-10">
                                            <input type="number" name="cvv" class="form-control" required>
                                    </div>
                            </div>

                            <br>

                            <div class="text-center">
                                <button type="submit" class="btn btn-secondary">Send</button>
                            </div>
                    </form>
            </div>
        </div>
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

templates/payment_app/status.html
{% extends 'payment_app/template.html' %}

{% load static %}
{% block content %}


<!--{% if error_message %}<p> <strong>{{ error_message }}</strong> </p>{% endif %}-->

{% if payment.started %}
<p>
<h1>Your payment has been initiated!</h1>

{{payment.credit_card_no}} <br>
{{payment.amount}}<br>
{{payment.payment_date}}<br>

<form action= "{% url 'payment_app:wait' payment.id %}" method="post">
    {% csrf_token %}
    <input type = "submit" value = "OK">
</form>

</p>

{% elif payment.ongoing %}
<h1>Your payment is being processed. Please wait for approval.</h1>
    

{% elif payment.approved %}
<h1>The following payment has been approved by the registration manager!</h1>
<br>
<h2>Please wait while the transaction is completed.</h2>
<br>
<!--
{{payment.credit_card_no}} <br>
{{payment.amount}}<br>
{{payment.payment_date}}<br>
-->

<form action= "{% url 'payment_app:complete' payment.id %}" method="post">
        {% csrf_token %}
        <input type = "submit" value = "Finish">
</form>

{% else %}
<h1>Your payment was successful! Thank you for joining us to the conference.</h1>

{% endif %}
</div>
{% endblock %}

templates/payment_app/success.html
{% extends 'payment_app/template.html' %}

{% load static %}
{% block content %}


<!--{% if error_message %}<p> <strong>{{ error_message }}</strong> </p>{% endif %}-->

{% if payment.started %}
<p>
<h1>Your payment has been initiated!</h1>

{{payment.credit_card_no}} <br>
{{payment.amount}}<br>
{{payment.payment_date}}<br>

<form action= "{% url 'payment_app:wait' payment.id %}" method="post">
    {% csrf_token %}
    <input type = "submit" value = "OK">
</form>

</p>

{% elif payment.ongoing %}
<h1>Your payment is being processed. Please wait for approval.</h1>


{% elif payment.approved %}
<h1>The following payment has been approved by the registration manager!</h1>
<br>
<h2>Please wait while the transaction is completed.</h2>
<br>
<!--
{{payment.credit_card_no}} <br>
{{payment.amount}}<br>
{{payment.payment_date}}<br>
-->

<form action= "{% url 'payment_app:complete' payment.id %}" method="post">
        {% csrf_token %}
        <input type = "submit" value = "Finish">
</form>

{% else %}
<h1>Your payment was successful! Thank you for joining us to the conference.</h1>

{% endif %}
</div>
{% endblock %}

templates/payment_app/template.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Home</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:index' %}">Back</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration_manager:display' %}">Show Payments</a>
                        </li>
                    -->
                    </ul>
                </div>
                <div class="mx-auto order-0">
                    <a class="navbar-brand mx-auto" href="#">Payment</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href=""></a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'payment_app:index' %}">Pay</a>
                        </li>
                    -->
                    </ul>
                </div>
            </nav>

    <main role="main" class="container">
        {% block content %}
        {% endblock %}

    </main><!-- /.container -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/payment_app/thankyou.html
{% load static %}
 <!DOCTYPE html>
<html lang="en">
   <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
     <title>Contact Us</title>
     <!-- Bootstrap core CSS -->
    <link href="{% static 'reviewer/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'reviewer/tabs.css' %}" rel="stylesheet">
    <link href="{% static 'reviewer/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  </head>
   <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <h2 style="color:aliceblue;">Contact Us</h2>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'track_chair:index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'authentication:index' %}">Back</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
 <!--{% if error_message %}<p> <strong>{{ error_message }}</strong> </p>{% endif %}-->
     <section id="tabs">
        <div class="container">
          <div class="row">
              <div class="col">
              </div>
              <p>
                <l>
                  <l>
              <h1>Thanks for writing in. We shall get back to you soon.</h1>
              </p>
 </html>