authentication/urls.py
from django.urls import path
from . import views
app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('choose_profile', views.choose_profile, name='choose_profile'),
    path('logout', views.logout_view, name='logout_view'),
    path('sign_up', views.sign_up, name='sign_up'),
]

author/urls.py
from django.urls import path
from django.conf.urls import include, url  
from . import views
from .views import index

app_name = 'author'

urlpatterns=[
     url('index', views.index,name="index"),
     path('<int:track_id>/edit',views.edit,name="edit"),
]

conference_system/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace="authentication")),
    path('author/', include('author.urls', namespace="author")),
    path('reviewer/', include('reviewer.urls', namespace="reviewer")),
    path('track_chair/', include('track_chair.urls', namespace="track_chair")),
    path('conference_chair/', include('conference_chair.urls', namespace="conference_chair")),
    path('registration_manager/', include('registration_manager.urls', namespace="registration_manager")),
    path('conference_manager/', include('conference_manager.urls', namespace="conference_manager")),
    path('payment_app/', include('payment_app.urls', namespace="payment_app")),
    path('email_system/',include('email_system.urls',namespace="email_system")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

email_system/urls.py
# sendemail/urls.py
from django.contrib import admin
from django.urls import path
from . import views
#app_name='sendemail'
app_name = 'email_system'
urlpatterns = [
    path('drafts/',views.display_draft,name='display'),
    path('customise/<int:pk>/',views.edit_draft,name='edit_draft'),
    
]

email_system/models.py
from django.db import models
 # Create your models here.
class draft(models.Model):
    title=models.CharField(max_length=500)
    text=models.CharField(max_length=500,null=True)

email_system/forms.py
from django import forms
from .models import draft
class DraftForm(forms.ModelForm):
    class Meta:
        model=draft
        fields=('title','text',)

email_system/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect,get_object_or_404
from django.conf import settings
from .models import draft
from .forms import DraftForm
from django.template import Context
from django.template.loader import get_template
app_name='email_system'

def display_draft(request):
    return render(request,"email_system/draft_templates.html")


def edit_draft(request,pk):
    data=get_object_or_404(draft,pk=pk)
    
    if request.method=="POST":
            form=DraftForm(request.POST,instance=data)
            if form.is_valid():
                data=form.save(commit=False)
                data.save()
            else:
                print("Form not valid")
    else:
        form= DraftForm(instance=data)
    return render(request,'email_system/edit_draft.html',{'form':form})

templates/email_system/draft_templates.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Conference Management System</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'reviewer/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/authentication/landing-page.css' %}" rel="stylesheet">
    <link href="{% static 'reviewer/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <style>
    a{
      color: black;
    }
    a:hover{
      text-decoration: none;
    }
    </style>
  </head>

  <body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="{% url 'authentication:index' %}">Welcome, {{request.user.first_name}}!</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'authentication:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'authentication:logout_view' %}">Log out</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <section class="features-icons bg-light text-center">
      <div class="container">
            <h2 style="font-family:'SFMono-Regular',Consolas,'Liberation Mono',Menlo,Courier,monospace;"class="text-center">Drafts</h2>
            <hr style="background:blue;height: 2px;"width="150px">
        <div class="row mx-auto">
          <div class="col-lg-4 mx-auto">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="fa fa-university m-auto text-primary"></i>
              </div>
              <h3><a href = "{% url 'email_system:edit_draft' pk=1 %}" >Registrations</a></h3>
            </div>
          </div>
          <div class="col-lg-4 mx-auto">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="fa fa-money m-auto text-primary"></i>
              </div>
              <h3><a href = "{% url 'email_system:edit_draft' pk=2 %}" >Payments</a></h3>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'author/bootstrap/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'author/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

templates/email_system/e_template.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <title>Home</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:index' %}">Back</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration_manager:display' %}">Show Payments</a>
                        </li>
                    -->
                    </ul>
                </div>
                <div class="mx-auto order-0">
                    <a class="navbar-brand mx-auto" href="#">Customisable Templates</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href=""></a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'payment_app:index' %}">Pay</a>
                        </li>
                    -->
                    </ul>
                </div>
            </nav>
     <main role="main" class="container">
        {% block content %}
        {% endblock %}
     </main><!-- /.container -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/email_system/edit_draft.html
{% extends 'email_system/e_template.html' %}
 {% block content %}
    <h2>Customise Draft</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}