authentication/urls.py
from django.urls import path
from . import views
app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('choose_profile', views.choose_profile, name='choose_profile'),
    path('logout', views.logout_view, name='logout_view'),
    path('sign_up', views.sign_up, name='sign_up'),
]

author/urls.py
from django.urls import path
from django.conf.urls import include, url  
from . import views
from .views import index

app_name = 'author'

urlpatterns=[
     url('index', views.index,name="index"),
     path('<int:track_id>/edit',views.edit,name="edit"),
]

conference_system/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace="authentication")),
    path('author/', include('author.urls', namespace="author")),
    path('reviewer/', include('reviewer.urls', namespace="reviewer")),
    path('track_chair/', include('track_chair.urls', namespace="track_chair")),
    path('conference_chair/', include('conference_chair.urls', namespace="conference_chair")),
    path('registration_manager/', include('registration_manager.urls', namespace="registration_manager")),
    path('conference_manager/', include('conference_manager.urls', namespace="conference_manager")),
    path('payment_app/', include('payment_app.urls', namespace="payment_app")),
    path('email_system/',include('email_system.urls',namespace="email_system")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'
urlpatterns = [

    path('', views.index, name='index'),
    path('<int:payment_id>/status', views.status, name='status'),
    path('<int:payment_id>/wait', views.wait, name='wait'),
    path('<int:payment_id>/approve', views.approve, name='approve'),
    path('<int:payment_id>/complete', views.complete, name='complete'),
]

registration_manager/urls.py
from django.urls import path
from . import views

app_name = 'registration_manager'

urlpatterns = [

    path('', views.display, name='display'),
    path('<int:payment_id>/approve', views.approve, name='approve'),
    path('<int:payment_id>/delete', views.delete, name = 'delete'),
    path('<int:user_id>/approve_user',views.approve_user,name='approve_user')
]

registration_manager/models.py
from django.db import models

# Create your models here.

registration_manager/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class collectPaymentForm(forms.Form):
    credit_card_no = forms.CharField(help_text = "Enter your credit card no.",max_length=20)
    amount = forms.IntegerField()
    cvv = forms.IntegerField()
    expiry_date = forms.DateField()

    def clean_expiry_date(self):
        data = self.cleaned_data['expiry_date']

        if data < datetime.date.today():
            raise ValidationError(_('Card expired!'))

        return data

        
    

registration_manager/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import get_object_or_404, render, redirect
from authentication.models import CustomUser
from django.http import HttpResponse
import datetime

from payment_app.models import Payment
from conference_manager.models import CustomUser

# Create your views here.

def display(request):
    payments = Payment.objects.all()
    roles = request.user.roles.all()
    users = CustomUser.objects.all()
    return render(request, 'registration_manager/display.html', {'payments':payments, 'roles':roles,'users':users})

def approve(request, payment_id):
    payment = get_object_or_404(Payment, pk = payment_id)
    payment.ongoing = False
    payment.approved = True
    payment.save()
    payments = Payment.objects.all()
    roles = request.user.roles.all()
    users = CustomUser.objects.all()
    return render(request, 'registration_manager/display.html',  {'payments':payments, 'roles':roles, 'users':users})

def approve_user(request, user_id):
    user_ = get_object_or_404(CustomUser, pk = user_id)
    user_.validated=True
    user_.save()
    payments = Payment.objects.all()
    roles = request.user.roles.all()
    users = CustomUser.objects.all()
    return render(request, 'registration_manager/display.html',  {'payments':payments, 'roles':roles,'users':users})


def delete(request, payment_id):
    Payment.objects.get(id=payment_id).delete()
    print(payment_id)
    payments = Payment.objects.all()
    roles = request.user.roles.all()
    users = CustomUser.objects.all()
    return render(request, 'registration_manager/display.html',  {'payments':payments, 'roles':roles, 'users':users})

templates/registration_manager/display.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Registration Manager</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'author/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'author/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">    
    <link href="{% static 'reviewer/tabs.css' %}" rel="stylesheet">
    <style>
    .nav-tabs > li, .nav-pills > li {
    float:none;
    display:inline-block;
}

.nav-tabs {
    text-align:center;
}
    </style>
  </head>
  <body>
      <nav style="border-bottom: 1px solid black;"class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id="mainNav">
          <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="{% url 'authentication:index' %}">Registration Manager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li style="float:right;" class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="{% url 'authentication:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li style="float: right;"class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="{% url 'authentication:logout_view' %}">Log out</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <section id="tabs">
        <div class="container">
            <br>
            <div class="row">
                <div class="col-xs-12 ">
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="false"><i class="fa-"></i>Payments</a>
                            <a class="nav-item nav-link active" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="true">Users</a>
                        </div>
                    </nav>
                    <div class="tab-content py-3 px-3" id="nav-tabContent">
                        <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                            {% if payments %}
                            <table class="table">
                                <thead>
                                  <tr>
                                    <th scope="col">Payment ID</th>
                                    <th scope="col">Credit Card Number</th>
                                    <th scope="col">CVV</th>
                                    <th scope="col">Expiry Date</th>
                                    <th scope="col">Time Stamp</th>
                                    <th scope="col">Amount(in Re)</th>
                                    <th scope="col">Approval Status</th>
                                    <th scope="col">Action</th>
                                  </tr>
                                </thead>
                                <tbody>        
                                    {% for payment in payments %}
                                    {% if payment.ongoing %}
                                  <tr>
                                    <th scope="row">{{payment.id}}</th>
                                    <td>{{payment.credit_card_no}}</td>
                                    <td>{{payment.cvv}}</td>
                                    <td>{{payment.expiry_date}}</td>
                                    <td>{{payment.payment_date}}</td>
                                    <td>{{ payment.amount}}</td>
                                    <td>No</td>
                                    <td>
                                        <form action= "{% url 'registration_manager:approve' payment.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="Submit" class="btn btn-outline-primary">Approve</button>
                                          </form>                                    
                                        </td>
                                  </tr>
                                  {% endif %}
                                  {% endfor %}
                                  {% for payment in payments %}
                                  {% if payment.approved %}
                                <tr>
                                  <th scope="row">{{payment.id}}</th>
                                  <td>{{payment.credit_card_no}}</td>
                                  <td>{{payment.cvv}}</td>
                                  <td>{{payment.expiry_date}}</td>
                                  <td>{{payment.payment_date}}</td>
                                  <td>{{ payment.amount}}</td>
                                  <td>Yes</td>
                                  <td>
                                      <form action= "{% url 'registration_manager:delete' payment.id %}" method="post">
                                          {% csrf_token %}
                                          <button type="Submit" class="btn btn-outline-danger">Remove</button>
                                      </form>
                                  </td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                            </table>
                            {% else %}
                            There are no payments made.
                            {% endif %}
                        </div>
                         
                        <div class="tab-pane fade show active" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                            {% if users %}
                            <table class="table">
                                <thead>
                                  <tr>
                                    <th scope="col">User ID</th>
                                    <th scope="col">Username</th>
                                    <th scope="col">Validation Status</th>
                                    <th scope="col">Action</th>
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for user in users %}
                                    {%if user.validated %}
                                    <p></p>
                                    {% else %}
                                  <tr>
                                    <th scope="row">{{ user.id }}</th>
                                    <td>{{user.username}}</td>
                                     
                                    <td>No</td>
                                    <td>
                                        <form action= "{% url 'registration_manager:approve_user' user.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="Submit" class="btn btn-outline-primary">Approve</button>
                                          </form>
                                    {% endif %}
                                    </tr>
                                {% endfor %}
                                {% for user in users %}
                                    {%if user.validated %}
                                  <tr>
                                    <th scope="row">{{ user.id }}</th>
                                    <td>{{user.username}}</td>
                                      
                                    <td>Yes</td>
                                    <td>
                                        <form action= "{% url 'registration_manager:approve_user' user.id %}" method="post">
                                            {% csrf_token %}
                                            <button disabled type="Submit" class="btn btn-outline-danger">Approved</button>
                                          </form>
                                    {% endif %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                          </table>
                            {% else %}
                            There are no users.
                            {% endif %}   
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
        </section>
</body>
<!-- Bootstrap core JavaScript -->
<script src="{% static 'author/bootstrap/jquery/jquery.min.js' %}"></script>
<script src="{% static 'author/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</html>

templates/registration_manager/index.html
{% extends 'registration_manager/template.html' %}

{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col-8">
            <div class="container-fluid" style="margin-top:10%;">
                    <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Credit Card Number</label>
                                <div class="col-sm-10">
                                        <input type="text" name="credit_card_no" class="form-control" required>
                                </div> 
                            </div>

                            <br>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Amount</label>
                                <div class="col-sm-10">
                                        <input type="number" name="amount" class="form-control" value= "200" required>
                                </div> 
                            </div>

                            <br>

                            

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Expiry date</label>
                                <div class="col-sm-10">
                                        <input type="date" name="expiry_date" class="form-control" required>
                                </div> 
                            </div>
                        
                            <br>     

                            <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">CVV</label>
                                    <div class="col-sm-10">
                                            <input type="number" name="cvv" class="form-control" required>
                                    </div> 
                            </div>

                            <br>
                            
                            <div class="text-center"> 
                                <button type="submit" class="btn btn-secondary">Pay</button>
                            </div>
                    </form>
            </div>
        </div>
        <div class="col">
        
        </div>
    </div>
</div>
{% endblock %}

templates/registration_manager/status.html
{% extends 'registration_manager/template.html' %}

{% load static %}
{% block content %}


<!--{% if error_message %}<p> <strong>{{ error_message }}</strong> </p>{% endif %}-->

{% if payment.started %}
<p>
<h1>Your payment has been initiated!</h1>

{{payment.credit_card_no}} <br>
{{payment.amount}}<br>
{{payment.payment_date}}<br>

<form action= "{% url 'registration_manager:wait' payment.id %}" method="post">
    {% csrf_token %}
    <input type = "submit" value = "OK">
</form>

</p>

{% elif payment.ongoing %}
<h1>Your payment is being processed. Please wait for approval.</h1>
    

{% elif payment.approved %}
<h1>The following payment has been approved by the registration manager!</h1>
<br>
<h2>Please wait while the transaction is completed.</h2>
<br>
<!--
{{payment.credit_card_no}} <br>
{{payment.amount}}<br>
{{payment.payment_date}}<br>
-->

<form action= "{% url 'registration_manager:complete' payment.id %}" method="post">
        {% csrf_token %}
        <input type = "submit" value = "Finish">
</form>

{% else %}
<h1>Your payment was successful! Thank you for joining us to the conference.</h1>
<!--
<form action= "{% url 'registration_manager:index' %}" method="post">
        {% csrf_token %}
        <input type = "submit" value = "Pay again">
</form>
-->
{% endif %}
</div>
{% endblock %}

templates/registration_manager/template.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Home</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:index' %}">Back</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration_manager:display' %}">Show Payments</a>
                        </li>
                    </ul>
                </div>
                <div class="mx-auto order-0">
                    <a class="navbar-brand mx-auto" href="#">Registration Manager</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href=""></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">Logout</a>
                        </li>
                    </ul>
                </div>
            </nav>

    <main role="main" class="container">
        {% block content %}
        {% endblock %}

    </main><!-- /.container -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>